### PR TITLE
Fixing opening draft and creating component

### PR DESCRIPTION
**Pull request by marcinbodnar**
1. It's fixing the problem with opening the file - now it's loading the draft version if exists.
2. Fixing margins.
3. Fix the way a new file is created.

### CODE REVIEW

**Review by milenakrawczyk — DISMISSED** [review]
I wasn't able to reproduce the previous bugs, however I found two new issues:
- When no component is present and I create a new component with a given name, this name is not assigned to the component. Instead a Draft-1 name is displayed.
- I can't create more than two components - I have Draft-1 and Draft-0 files and when I click "Create a new component", nothing happens.

**Comment by marcinbodnar** [comment]
> I wasn't able to reproduce the previous bugs, however I found two new issues:
> 
> * When no component is present and I create a new component with a given name, this name is not assigned to the component. Instead a Draft-1 name is displayed.
> * I can't create more than two components - I have Draft-1 and Draft-0 files and when I click "Create a new component", nothing happens.

Fixed.

**Review by calebjacob — APPROVED** [review]
Everything looks good after playing around with it for a bit. Thanks for the fix @marcinbodnar! I'll let you know if I see the bug pop up again.

**Comment by marcinbodnar** [comment]
Thanks you @calebjacob

**Comment by marcinbodnar** [comment]
- the main problem was with Draft-X files - I removed this mechanism and added Untitled-X and it’s working differently from the implementation point of view
 - change Creating New File flow - now you are not able to provide the name but you are able to rename it immediately - so it’s similar to how most of the ide’s a working
 - splash page
 - fixing drafts mechanism

**Comment by charleslavon** [comment]
LGTM 👍🏾 🚀

**Pull request merged**
