### PR TITLE
chore: Swap out alpha search bar with chaotictempest

### PR DESCRIPTION
**Pull request by ChaoticTempest**
swaps out the current search implementation on alpha with the one from Discovery-Discovery team

### CODE REVIEW

**Comment by ChaoticTempest** [comment]
Added the references to `widgets.js`, but don't know how it can be used directly since we have `NavigationButton`. Also, didn't see where you sent the `one.testnet` account, so I pushed it to my `welp.testnet` account instead. Feel free to move it over to `one.testnet` in the mean time, since I'll be OOO till this coming tuesday

**Comment by Patrick1904** [comment]
> found some time to move it over to the `one.testnet` account you send me @Patrick1904. Let me know if it's good to go

Thank you! Can you please change the merge request from `main` to the `develop` branch?

**Comment by ChaoticTempest** [comment]
done

**Review by Patrick1904 — APPROVED** [review]
LGTM

**Pull request merged**
